hugoblox:
  schema: "2.0"
  identity:
    name: Omodolapo Victor Babalola
    type: person
    tagline: IT Engineer and Researcher
    description: His research interest lies in the intersection of Artificia Intelligence, security, privacy, federated learning and autonomy.
  theme:
    mode: system
    pack: synthwave
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: serif
    size: lg
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
